AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    fiap-aws
Globals:
    Function:
        Timeout: 20
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/fiap-aws-1.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: com.fiap.aws.handler.CreateTripRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable   
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trip
           Method: post
           
  GetTripRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/fiap-aws-1.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: com.fiap.aws.handler.GetTripRecordsByPeriod::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable   
     Events:
       GetTripRecordsByPeriod:
         Type: Api
         Properties:
           Path: /trip
           Method: get
           RequestParameters:
              - method.request.querystring.start
              - method.request.querystring.end            
  GetTripRecordsByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/fiap-aws-1.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: com.fiap.aws.handler.GetTripRecordsCountry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable
     Events:
       GetTripRecordsByCountry:
         Type: Api
         Properties:
           Path: /trip/{country}
           Method: get
           RequestParameters:
              - method.request.querystring.country
  GetTripRecordsByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: target/fiap-aws-1.0-SNAPSHOT-jar-with-dependencies.jar
     Handler: com.fiap.aws.handler.GetTripRecordsByCountry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable
     Events:
       GetTripRecordsByCountry:
         Type: Api
         Properties:
           Path: /trip/{country}
           Method: get
           RequestParameters:
              - method.request.querystring.country
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: trip
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: country
          AttributeType: S      
        - AttributeName: reason
          AttributeType: S            
      KeySchema:
        - AttributeName: trip
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: countryIndex
          KeySchema: 
            - AttributeName: trip
              KeyType: HASH
            - AttributeName: country
              KeyType: RANGE
          Projection:
             ProjectionType: ALL 
        - IndexName: cityIndex
          KeySchema: 
            - AttributeName: trip
              KeyType: HASH
            - AttributeName: city
              KeyType: RANGE
          Projection:
             ProjectionType: ALL      
        - IndexName: reasonIndex
          KeySchema: 
            - AttributeName: trip
              KeyType: HASH
            - AttributeName: reason
              KeyType: RANGE
          Projection:
             ProjectionType: ALL      
      BillingMode: PAY_PER_REQUEST              

Outputs:
    CreateTripRecordFunction:
      Description: "CreateTripRecord Lambda Function ARN"
      Value: !GetAtt CreateTripRecordFunction.Arn
      
    GetTripRecordsByPeriodFunction:
      Description: "GetTripRecordsByPeriod Lambda Function ARN"
      Value: !GetAtt GetTripRecordsByPeriodFunction.Arn
      
    GetTripRecordsByCountryFunction:
      Description: "GetTripRecordsByCountry Lambda Function ARN"
      Value: !GetAtt GetTripRecordsByCountryFunction.Arn
      
    GetTripRecordsByCityFunction:
      Description: "GetTripRecordsByCity Lambda Function ARN"
      Value: !GetAtt GetTripRecordsByCityFunction.Arn      